### ISSUE TITLE
how to give same color as each set and point 

### ISSUE THREAD

**Issue by Hemantcnaik** [krassowski/complex-upset#115]
Hello I wanted use complex-upset plot as mentioned in the below link is it possible to do like that.
I saw the 9.1 example but its not same as I wanted can you please help me to figure it out, when I tried plot gave me repeated sets I don't want like that, if you see the image in the link it should be like that can you please help me

[https://stackoverflow.com/questions/67094573/upsetr-sets-bar-interacting-different-color-and-its-sets-intersections]()

**Comment by krassowski** [comment]
Thanks for opening this issue. After updating to the latest development version with:

```R
if(!require(devtools)) install.packages("devtools")
devtools::install_github("krassowski/complex-upset")
```

You should be able to use `upset_query()` to achieve the intended effect:

```R
set_size(5, 3.6)
upset(
  movies,
  c('Action', 'Comedy', 'Drama'),
  queries=list(
    upset_query(set='Action', color='orange', fill='orange'),
    upset_query(set='Comedy', color='blue', fill='blue'),
    upset_query(set='Drama', color='coral3', fill='coral3')
  )
)
```

<img src="https://user-images.githubusercontent.com/5832902/116778562-8506c200-aa6a-11eb-8a47-25334b3489ed.png" width=400>

I also responded in the Stack Overflow post providing more detailed hints on reproducing the example plot and demonstrating how to use `fill` instead of `color` + `shape=circle filled` to prevent the connector segments from getting coloured.
