### ISSUE TITLE
input list of genes/SNPs/clonotypes

### ISSUE THREAD

**Issue by gt7901b** [krassowski/complex-upset#157]
**Objective**
how to use the complex-upset when the inputs are columns of genes such as

Control	Treatment1	Treatment2
IL21	       CD200	       TNFRSF4
SRGN	EGR2	       SNX9
NFKBID	SIAH2	         CFLAR
IRF4	LIF	NR4A1          YWHAQ
PIM3	RNF19A	     KDM6B
FRMD4B	SLA	              NDFIP2
YWHAQ	TNFRSF4	IL2

thanks

**Code**

```R
Please replace this line by any code that may illustrate your attempts at solving the issue.
```

**Screenshot or illustration**

**Context (required)**

ComplexUpset version: x.x.x

<details>
<summary>R version details</summary>

```R
<!-- Please replace this line by output of R.Version() -->
```

</details>

<details>
<summary>R session information</summary>

```R
<!-- Please replace this line by output of sessionInfo() -->
```

</details>

**Comment by krassowski** [comment]
Hi @gt7901b sorry I missed your question earlier. I don't understand what you are asking. Could you please clarify by providing more details/example input → expected outcome?

**Comment by krassowski** [comment]
I will close this one due to lack of follow up, I hope it worked out well. I think that an answer for your question is in https://github.com/krassowski/complex-upset/issues/166#issuecomment-1366904848 although it was not very clear for me originally what you were asking - sorry.

Thanks for opening the issue though!
