### ISSUE TITLE
Don't use hyphens in variable names

### ISSUE THREAD

**Issue by samlipworth** [krassowski/complex-upset#32]
I don't know why it behaves like this, but if you use eg Co-amoxiclav instead of Co amoxiclav - you get an incorrect upset plot where all of the points of Co-amoxiclav are missing. Using Co amoxiclav fixes this. Took me about an hour to work out what was going on here so hopefully helpful to someone else (maybe even easily fixable).

**Comment by krassowski** [comment]
@samlipworth sincere apologies for the time you lost on this. I have now fixed this issue and added two tests to ensure it will now happen again. This has been just published as v0.5.10 - you can update the package using:

```
devtools::install_github("krassowski/complex-upset")
```

Thank you for taking time to notify me about it, and for giving heads up to other users.

I hope that otherwise you enjoy this package. Please let me know of any other things you would consider worth improving.

**Comment by samlipworth** [comment]
No worries - thanks for fixing it! The package is great so thanks a lot for making it.
