### ISSUE TITLE
Total numer of cases

### ISSUE THREAD

**Issue by cristobalcar** [krassowski/complex-upset#44]
Hello, I was wondering if you can add the total numer of cases in the insersection size plot. I mean the sum() each intersection size.
Thanks!

**Comment by krassowski** [comment]
This seems like a very reasonable example request! A few questions to think about:
- where on the upset plot would you like to display it?
- should it always count all data points, or if filtering of intersections/groups is used, only the displayed ones?

**Comment by cristobalcar** [comment]
I'm thinking maybe in a geom_lael in this location...
<img width="692" alt="Screen Shot 2020-06-25 at 13 27 46" src="https://user-images.githubusercontent.com/29803674/85769117-b3e43700-b6e7-11ea-81d9-208a4678eff2.png">
I think also it should count all the displayed results

**Comment by krassowski** [comment]
One solution would be to add an annotation to the geoms list. In order to keep the benefits of intersection_size autogenerated aes/geom one can just modify the geoms list as follows:

```R
isize = intersection_size(text=list(angle=90, vjust=0.5, hjust=0))
isize$geom = c(
    isize$geom,
    annotate(geom='text', x=Inf, y=Inf, label=nrow(movies), vjust=1, hjust=1)
)

upset(
    movies, genres, name='genre', min_size=100,
    base_annotations =list(
        'Intersection size'=isize
    )
)
```

which will not necessarily play nice with filtering but should be easy enough to modify/improve. Example:

![image](https://user-images.githubusercontent.com/5832902/85810527-4110a580-b753-11ea-9b04-9809de8e35d1.png)

I will think about this use-case during the upcoming `intersection_size` redesign.

**Comment by cristobalcar** [comment]
works perfect!
Thanks again
