### ISSUE TITLE
suppress messages when knitting in rmarkdown

### ISSUE THREAD

**Issue by taylorreiter** [krassowski/complex-upset#53]
Hello! I'm knitting my upset plot with rmarkdown, but the following text is printed to the document:

```
"Converting non-logical columns to binary: X Y Z"
```

Is it possible to suppress this message? I have `message` set to `F`, but it still escapes and is printed in the document

```
knitr::opts_chunk$set(echo = F, eval = T, message = F, warning = F, cache = T, 
                      include = T, fig.keep = 'high', fig.path = "Rmd_fig_out/",
                      dpi=400)
```

**Comment by krassowski** [comment]
Sorry about this! I will convert this to a proper warning so that it can be suppressed in the next version. For now the best workaround is to convert the columns to logical, for example:

```R
library(ggplot2)
library(ComplexUpset)

movies = ggplot2movies::movies
movies[movies$mpaa == '', 'mpaa'] = NA
movies = movies[complete.cases(movies), ]
genres = c(
    'Action', 'Animation', 'Comedy', 'Drama',
    'Documentary', 'Romance', 'Short'
)
upset(movies, genres, name='genre', width_ratio=0.1)
```

will print `[1] "Converting non-logical columns to binary: Action, Animation, Comedy, Drama, Documentary, Romance, Short"`

but if you do:

```R
movies[genres] = movies[genres] == 1
upset(movies, genres, name='genre', width_ratio=0.1)
```

the message will no longer show up.

**Comment by taylorreiter** [comment]
Thank you!
