### ISSUE TITLE
How to change y axis category names of the intersection matrix 

### ISSUE THREAD

**Issue by akhst7** [krassowski/complex-upset#69]
HI,

I tried using `ylab() and labs(y="")`   charge/rename y axis title but did not work at all.    I'd really appreciate I you could give me some examples. 

Thanks always.

**Comment by krassowski** [comment]
I do not understand what you want to achieve. Please do explain your question more clearly and with more details and examples next time.

If you wish to change the `ylab` of intersection size:
```R
upset(
    movies,
    genres,
    base_annotations=list(
        'Some text'=intersection_size(counts=FALSE)
    ),
    min_size=100
)
```

![Screenshot from 2020-11-30 13-26-07](https://user-images.githubusercontent.com/5832902/100615565-a9217400-330f-11eb-9dd8-1c1d8fbb5aea.png)


Intersection matrix has no ylab, so the title of this issue is confusing. If you wish to change the xlab you can use:
```R
upset(
    movies,
    genres,
    min_size=100
) + xlab('Some text')
```

![Screenshot from 2020-11-30 13-26-53](https://user-images.githubusercontent.com/5832902/100615602-b9395380-330f-11eb-89ba-a9af55249ee4.png)

If you want to change how the set names are displayed, you can use labeller

```R
upset(
    movies,
    genres,
    min_size=100,
    labeller=function(labels) { paste(labels, 'movie') }
)
```

![Screenshot from 2020-11-30 13-29-34](https://user-images.githubusercontent.com/5832902/100615841-192ffa00-3310-11eb-9fc1-45e63e12605e.png)

Potential duplicate of #61.

**Comment by akhst7** [comment]
@krassowski ,

Labeller was the one needed.   

Thanks.

**Comment by mattflor** [comment]
Is there a way to change the "Set size" axis title, too? I can't figure it out...

**Comment by mattflor** [comment]
Ok, I found a way :)
```r
upset(
  movies,
  genres,
  set_sizes = upset_set_size() + ylab("Alternative axis title")
)
```

**Comment by krassowski** [comment]
Happy you found a solution :) I will probably replace `coord_flip()` with `orientation` in the next major version so it will become more intuitive `xlab()` (keeping it the old way for now for compatibility with older ggplot2 versions).

Please feel welcome to ask any other questions or provide feedback on your experience using this package :)

**Comment by Bingqing-Yang** [comment]
Hello, I want to ask how to change the text size of 'intersection size' in intersection panel. Thank you for your sharing.
