### ISSUE TITLE
cannot fill by group for set size plot

### ISSUE THREAD

**Issue by lijing28101** [krassowski/complex-upset#86]
I want to make the plot using the same code as documentation:

```
upset(
    movies, genres,
    min_size=10,
    width_ratio=0.3,
    set_sizes=(
        upset_set_size(
            geom=geom_bar(
                aes(fill=mpaa, x=group),
                width=0.8
            ),
            position='right'
        )
    )
)
```
But it gave me the error:
```
Error in FUN(X[[i]], ...) : object 'mpaa' not found
```
 The same error happened when I work on my own data.

**Comment by krassowski** [comment]
Which version do you have installed?

**Comment by lijing28101** [comment]
Hi @krassowski ,

I might used an old version when I installed from CRAN.
The problem is fixed when I install from github.

**Comment by krassowski** [comment]
Happy it works for you now. I'm sorry the CRAN version is outdated but they do not accept new versions during the holiday period (see https://cran.r-project.org/submit.html) and I just cannot upload it before January 4th because the submission system is turned off.

As it is resolved, I will close this issue. Thanks for getting back to me!
